name: Container image build
on:
  # build when push to main or release happens
  push:
    branches:
      - main

  # allow manual execution
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
    IMAGE_NAME: yocto-build-env
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v3

      # Build image using Buildah action
      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest ${{ github.sha }}
          oci: true
          context: .
          containerfiles: |
            ./Containerfile

      # Push the image to GHCR (Image Registry)
      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust

      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"
